main: com.cavetale.capturetheflag.CaptureTheFlagPlugin
name: CaptureTheFlag

version: ${version}
api-version: '1.20'

author: StarTux
website: https://github.com/StarTux/CaptureTheFlag
description: CaptureTheFlag Plugin

depend: [Core, Creative, Mytems, Title, Area, Fam]
softdepend: []

commands:

  capturetheflag:
    aliases: [ctf]
    description: CaptureTheFlag Command
    permission: ctf.ctf
    usage: /ctf

  capturetheflagadmin:
    aliases: [ctfadm]
    description: Admin Command
    permission: ctf.admin
    usage: /ctfadm

permissions:

  ctf.ctf:
    description: Use /ctf
    default: op

  ctf.admin:
    description: Use /ctfadm
    default: op
